version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:1.10.0
    ports:
      - "7233:7233"
    environment:
      - DB=sqlite3
    networks:
      - temporal-streamlit-net

  ui:
    build:
      context: ./ui
    ports:
      - "8501:8501"
    depends_on:
      - temporal
    env_file:
      - ./ui/.env
    networks:
      - temporal-streamlit-net
    command: streamlit run app.py

  worker:
    build:
      context: ./ui
    depends_on:
      - temporal
    env_file:
      - ./ui/.env
    networks:
      - temporal-streamlit-net
    command: python worker.py

networks:
  temporal-streamlit-net:
    driver: bridge
